env:
  browser: true
  es2021: true
  node: true
globals:
  React: true
  ReactDOM: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
settings:
  react:
    version: 'detect'
plugins:
  - react
rules:
  react/prop-types: off
